### ISSUE TITLE
Is this repo now obsolete?

### ISSUE THREAD

**Issue by tonytheodore** [vanrein/asn2quickder#6]
I notice that quick-der now seems to bundle it's own https://github.com/vanrein/quick-der/blob/master/python/scripts/asn2quickder

**Comment by vanrein** [comment]
Hi Tony,

Yes, this repository is now obsolte because:

 1. asn1ate moved to be a generic library with sufficient functionality (IMPORTS / EXPORTS) to translate RFCs
 2. since asn1ate is a library, it made sense to incorporate asn2quickder with Quick DER, https://github.com/vanrein/quick-der/

I will update this repository with a README to say just that (but without destorying the repository or the work done in it, just deleting files in a new commit).

We found a few small differences, usually variables set to None by the new asn1ate and to [] by the code in here.

I'm surprised about your fast inquiry :) so if you're using Quick DER in your own setup, I'd enjoy hearing about what you use it for, and if it works well for you.

Cheers,
 -Rick

**Comment by vanrein** [comment]
I switched the default branch shown on github to "dissolved".  The "master" branch is left untouched, so as to not get users, if any, into trouble.

**Comment by tonytheodore** [comment]
Thanks Rick, the restructuring makes sense.

I don't use Quick DER myself, just started trying to package it in the past day or two and was having issues so decided to switch the development branches. I'm reviving an [abandoned PR adding TLS Pool to MXE for cross compilation](https://github.com/mxe/mxe/pull/1560).

**Comment by vanrein** [comment]
Hi Tony,

Ah, thanks for that.  Do ask Henri if you need support with that, he's done the MXE port for us.

-Rick
